Finished the Newsweek
emasdev/newsweek-clone pull request #5
Opened 2020-05-08 23:15 UTC by emasdev

Finished the Frontpage of Newsweek page using almost bootstrap framework.
It has a header, a main news section, some grids, newsletter section, and footer.

Everything is responsive

2020-05-09 15:40 UTC, rammazzoti2000 commented
### Pull Request under the review by Alexandru Bangau :raised_hands:

2020-05-09 16:32 UTC, rammazzoti2000 requested changes
### Hello @emasdev I am Alex, your code reviewer for this project :raised_hands: 
Your project looks amazing, you made great use of HTML semantic, and is impressive how much you used bootstrap.
Your readme is descriptive, the pull request has meaningful title and description, the repo overall looks professional, I just wonder how come so few commits for such a big project :question: 
Anyway, there are some issues that are preventing me from approving this project
### :stop_sign:  Required Changes :construction: :construction_worker: 
- [x] The HTML code is not passing validation, it should pass validation using this recommended [validator](https://validator.w3.org/#validate_by_input)  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
![image](https://user-images.githubusercontent.com/3244654/81478912-8bc87380-9220-11ea-9a17-cc8f1ae0ff1d.png)
- [x] The title for each section should be a bit bolder, it seems they are quite light with respect to the original
- [x] The links section in the navbar should stretch to the whole width
#### Clone:
![image](https://user-images.githubusercontent.com/3244654/81479011-2a54d480-9221-11ea-8a03-5f91911b8320.png)
#### Original:
![image](https://user-images.githubusercontent.com/3244654/81479025-3f316800-9221-11ea-9d58-2abf08e231fd.png)
- [x] On mobile screen the Featured Stories switches with the Top Stories, the first section from the top should be Top Stories
- [x] The social buttons in the footer when on medium screens are not properly aligned
#### Clone:
![image](https://user-images.githubusercontent.com/3244654/81479216-4442e700-9222-11ea-9e8e-0e9a22787478.png)
#### Original:
![image](https://user-images.githubusercontent.com/3244654/81479241-663c6980-9222-11ea-9b5a-1179b96d5878.png)
- [x] On mobile screens the page is not displaying properly, including the navbar, you can see that just under 500px from the screenshot bellow
![image](https://user-images.githubusercontent.com/3244654/81479340-e367de80-9222-11ea-8b34-02c047948774.png)
####
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

##### Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>

### :stop_sign:  Status: Changes required.

2020-05-09 16:32 UTC, rammazzoti2000 commented on style.css
> +  border-top: 4px solid #f92859 !important;
You should not use `!important` property

2020-05-09 16:32 UTC, rammazzoti2000 commented on style.css
> +  border-top: 4px solid #1c87fb !important;
You should not use `!important` property

2020-05-09 16:40 UTC, rammazzoti2000 requested changes
#### :stop_sign: Status: Required Changes

2020-05-11 20:51 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-05-11 21:07 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @emasdev, great job :1st_place_medal:  The project looks great :+1: However, let us improve the project and make it even better. :smile: 
- Kindly address the comments by the previous TSE for which he talked about content not displaying properly on-screen < 500px on ( mobile device), including the subscribe button and the login
```Currently```
![c](https://user-images.githubusercontent.com/46388113/81611634-eac9ec00-93ca-11ea-8898-592bd7175d54.png)
```Original```
![o](https://user-images.githubusercontent.com/46388113/81611660-f4ebea80-93ca-11ea-8b64-e2fbd42dcbd3.png)

[OPTIONAL]
Kindly follow this order on mobile device => Top story, Featured stories, Opinion, More stories, Heroes of the pandemic, Latest News, In the magazine

Kindly address this issue and submit another code review :smile: 
_Happy coding_ :man_technologist: 
Daniel Larbi Addo on slack

2020-05-12 00:47 UTC, serdg0 approved these changes
**Congratulations** @emasdev  :fireworks: :100: :fireworks:
Feel free to merge.
Keep the good work in your next project!
**Happy Coding!** :computer: :nerd_face:
**_Sergio Diaz_**

2020-05-12 01:50 UTC, merged